### ISSUE TITLE
Time output is not formatted for two characters

### ISSUE THREAD

**Issue by whimboo** [davehunt/dashiell#1]
When you issue the `activity` command the reply is wrongly formatted for the time and only returns a single char for seconds < 10: `distance 10.6km (6.6mi), pace 5:5/km (8:11/mi)`. This may also be true for minutes if its longer than 1h.

**Comment by davehunt** [comment]
This was fixed in 21f2d3ecb74365c350747e1edf1a3a031f3effbf
